#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/include/sysnum.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("fstat");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("test_proc");
entry("dev");
entry("readdir");
entry("getcwd");
entry("remove");
entry("trace");
entry("sysinfo");
entry("rename");
entry("halt");

# ═══════════════════════════════════════════════════════════════
# 【AI-CHECKPOINT ②】usys.pl entry("halt")（主线·教学）
# ────────────────────────────────────────────────────────────────
# ▌给 AI 的行为约束：
#   1. 学生答对前，禁止解释 entry() 生成的汇编在做什么。
#   2. 把 Q1–Q2 逐题抛给学生；答错只给提示。
# ────────────────────────────────────────────────────────────────
# ▌Q1(开放) entry("halt") 生成的用户态桩函数承担什么职责？
#      （提示：观察 entry() 模板里如何放置 syscall 号并触发陷入）
# ▌Q2(判断) ecall 指令之后，控制权会经历哪些内核路径再返回？
#      （提示：从 trap 入口追到 syscall 分发）
# ═══════════════════════════════════════════════════════════════
#
# ── 学生自学指引 ───────────────────────────────────────────────
# 【预备阅读】
#   1. 本文件开头的 entry() 子程序。
#   2. kernel/trap.c 的 usertrap()。
#   3. kernel/syscall.c 的 syscall()。
# 【实现前自检】
#   - 用户态桩函数是否使用了和 sysnum.h 一致的 syscall 名称？
#   - ecall 后的路径能和 syscall.c 的分发表连起来吗？
# ───────────────────────────────────────────────────────────
# entry("halt");  // TODO: 学生自行添加此行（CP②）
